"""

Revision ID: 033826a086f1
Revises: e36c9753b09e
Create Date: 2026-04-16 00:14:11.743403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033826a086f1'
down_revision: Union[str, Sequence[str], None] = 'e36c9753b09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_parts', sa.Column('part_name', sa.String(length=150), nullable=False))
    op.alter_column('repair_parts', 'unit_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('repair_parts', 'total_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.drop_column('repair_parts', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_parts', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.alter_column('repair_parts', 'total_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('repair_parts', 'unit_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.drop_column('repair_parts', 'part_name')
    # ### end Alembic commands ###
