"""

Revision ID: 21503d83ca96
Revises: b8e719bcee2e
Create Date: 2026-04-11 00:49:56.948547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21503d83ca96'
down_revision: Union[str, Sequence[str], None] = 'b8e719bcee2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'created_at')
    op.drop_column('refresh_tokens', 'expires_at')
    op.drop_column('refresh_tokens', 'is_revoked')
    # ### end Alembic commands ###
