"""

Revision ID: 30ea20601c53
Revises: e435e08b9d03
Create Date: 2026-05-16 20:40:05.269649

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30ea20601c53"
down_revision: str | Sequence[str] | None = "e435e08b9d03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asset_categories", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    op.drop_index(op.f("ix_asset_categories_code"), table_name="asset_categories")
    op.create_index(
        op.f("ix_asset_categories_slug"), "asset_categories", ["slug"], unique=True
    )
    op.drop_column("asset_categories", "code")
    op.add_column(
        "asset_classes", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    op.drop_constraint(op.f("uq_asset_classes_code"), "asset_classes", type_="unique")
    op.create_index(
        op.f("ix_asset_classes_slug"), "asset_classes", ["slug"], unique=True
    )
    op.drop_column("asset_classes", "code")
    op.add_column(
        "asset_models", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    op.drop_constraint(op.f("uq_asset_models_code"), "asset_models", type_="unique")
    op.create_index(op.f("ix_asset_models_slug"), "asset_models", ["slug"], unique=True)
    op.drop_column("asset_models", "code")
    op.add_column("assets", sa.Column("slug", sa.String(length=255), nullable=False))
    op.drop_index(op.f("ix_assets_asset_tag"), table_name="assets")
    op.drop_index(op.f("ix_assets_type"), table_name="assets")
    op.create_index(op.f("ix_assets_slug"), "assets", ["slug"], unique=True)
    op.drop_column("assets", "type")
    op.drop_column("assets", "asset_tag")
    op.add_column(
        "manufacturers", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    op.drop_constraint(op.f("uq_manufacturers_code"), "manufacturers", type_="unique")
    op.create_index(
        op.f("ix_manufacturers_slug"), "manufacturers", ["slug"], unique=True
    )
    op.drop_column("manufacturers", "code")
    op.add_column(
        "permissions", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.create_index(op.f("ix_permissions_slug"), "permissions", ["slug"], unique=True)
    op.drop_column("permissions", "code")
    op.add_column("regions", sa.Column("slug", sa.String(length=255), nullable=False))
    op.create_index(op.f("ix_regions_slug"), "regions", ["slug"], unique=True)
    op.add_column("roles", sa.Column("slug", sa.String(length=255), nullable=False))
    op.drop_index(op.f("ix_roles_code"), table_name="roles")
    op.create_index(op.f("ix_roles_slug"), "roles", ["slug"], unique=True)
    op.drop_column("roles", "code")
    op.add_column("services", sa.Column("slug", sa.String(length=255), nullable=False))
    op.drop_constraint(op.f("uq_services_code"), "services", type_="unique")
    op.create_index(op.f("ix_services_slug"), "services", ["slug"], unique=True)
    op.drop_column("services", "code")
    op.add_column(
        "warehouses", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    op.drop_constraint(op.f("uq_warehouses_code"), "warehouses", type_="unique")
    op.create_index(op.f("ix_warehouses_slug"), "warehouses", ["slug"], unique=True)
    op.drop_column("warehouses", "code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "warehouses",
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_warehouses_slug"), table_name="warehouses")
    op.create_unique_constraint(
        op.f("uq_warehouses_code"),
        "warehouses",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("warehouses", "slug")
    op.add_column(
        "services",
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_services_slug"), table_name="services")
    op.create_unique_constraint(
        op.f("uq_services_code"),
        "services",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("services", "slug")
    op.add_column(
        "roles",
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_roles_slug"), table_name="roles")
    op.create_index(op.f("ix_roles_code"), "roles", ["code"], unique=True)
    op.drop_column("roles", "slug")
    op.drop_index(op.f("ix_regions_slug"), table_name="regions")
    op.drop_column("regions", "slug")
    op.add_column(
        "permissions",
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_permissions_slug"), table_name="permissions")
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)
    op.drop_column("permissions", "slug")
    op.add_column(
        "manufacturers",
        sa.Column("code", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_manufacturers_slug"), table_name="manufacturers")
    op.create_unique_constraint(
        op.f("uq_manufacturers_code"),
        "manufacturers",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("manufacturers", "slug")
    op.add_column(
        "assets",
        sa.Column(
            "asset_tag", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "assets",
        sa.Column("type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_assets_slug"), table_name="assets")
    op.create_index(op.f("ix_assets_type"), "assets", ["type"], unique=False)
    op.create_index(op.f("ix_assets_asset_tag"), "assets", ["asset_tag"], unique=True)
    op.drop_column("assets", "slug")
    op.add_column(
        "asset_models",
        sa.Column("code", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_asset_models_slug"), table_name="asset_models")
    op.create_unique_constraint(
        op.f("uq_asset_models_code"),
        "asset_models",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("asset_models", "slug")
    op.add_column(
        "asset_classes",
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_asset_classes_slug"), table_name="asset_classes")
    op.create_unique_constraint(
        op.f("uq_asset_classes_code"),
        "asset_classes",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("asset_classes", "slug")
    op.add_column(
        "asset_categories",
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_asset_categories_slug"), table_name="asset_categories")
    op.create_index(
        op.f("ix_asset_categories_code"), "asset_categories", ["code"], unique=True
    )
    op.drop_column("asset_categories", "slug")
    # ### end Alembic commands ###
