"""

Revision ID: 31c6372d020c
Revises: 
Create Date: 2026-05-03 22:09:51.251018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c6372d020c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['asset_categories.id'], name=op.f('fk_asset_categories_parent_id_asset_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_categories'))
    )
    op.create_index(op.f('ix_asset_categories_code'), 'asset_categories', ['code'], unique=True)
    op.create_table('asset_classes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_classes')),
    sa.UniqueConstraint('code', name=op.f('uq_asset_classes_code'))
    )
    op.create_index('uq_asset_class_name_lower', 'asset_classes', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('manufacturers',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers')),
    sa.UniqueConstraint('code', name=op.f('uq_manufacturers_code'))
    )
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=False)
    op.create_index('uq_manufacturer_name_lower', 'manufacturers', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('ranks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranks')),
    sa.UniqueConstraint('code', name=op.f('uq_ranks_code')),
    sa.UniqueConstraint('name', name=op.f('uq_ranks_name'))
    )
    op.create_table('regions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geojson', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['regions.id'], name=op.f('fk_regions_parent_id_regions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('name', name=op.f('uq_regions_name'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('services',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('code', name=op.f('uq_services_code')),
    sa.UniqueConstraint('name', name=op.f('uq_services_name'))
    )
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configs'))
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('asset_models',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('lifetime_years', sa.Integer(), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], name=op.f('fk_asset_models_category_id_asset_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_asset_models_manufacturer_id_manufacturers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_models')),
    sa.UniqueConstraint('code', name=op.f('uq_asset_models_code')),
    sa.UniqueConstraint('name', 'manufacturer_id', name='uq_model_manufacturer')
    )
    op.create_index(op.f('ix_asset_models_category_id'), 'asset_models', ['category_id'], unique=False)
    op.create_index(op.f('ix_asset_models_manufacturer_id'), 'asset_models', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_asset_models_name'), 'asset_models', ['name'], unique=False)
    op.create_index('uq_asset_model_name_lower', 'asset_models', [sa.literal_column('lower(name)'), 'manufacturer_id'], unique=True)
    op.create_table('region_services',
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_region_services_region_id_regions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_region_services_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('region_id', 'service_id', name=op.f('pk_region_services'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_region_id', sa.UUID(), nullable=True),
    sa.Column('assigned_service_id', sa.UUID(), nullable=True),
    sa.Column('rank_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('dismissed_at', sa.Date(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_region_id'], ['regions.id'], name=op.f('fk_users_assigned_region_id_regions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_service_id'], ['services.id'], name=op.f('fk_users_assigned_service_id_services'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], name=op.f('fk_users_rank_id_ranks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('badge_number', name=op.f('uq_users_badge_number')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login')),
    sa.UniqueConstraint('passport_number', name=op.f('uq_users_passport_number')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('approval_requests',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approval_status'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_approval_requests_approved_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_approval_requests_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_action'), 'approval_requests', ['action'], unique=False)
    op.create_index(op.f('ix_approval_requests_approved_by_id'), 'approval_requests', ['approved_by_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_created_by_id'), 'approval_requests', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_entity_id'), 'approval_requests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_entity_type'), 'approval_requests', ['entity_type'], unique=False)
    op.create_index('ix_approval_status_created', 'approval_requests', ['status', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_path'), 'audit_logs', ['path'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_resets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_resets'))
    )
    op.create_index(op.f('ix_password_resets_expires_at'), 'password_resets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('idx_refresh_user_active', 'refresh_tokens', ['user_id', 'is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_user_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', name=op.f('pk_user_permissions'))
    )
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('manager_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], name=op.f('fk_warehouses_manager_user_id_users')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_warehouses_region_id_regions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_warehouses_service_id_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouses_code'))
    )
    op.create_table('assets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('asset_tag', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'assigned', 'in_repair', 'archived', name='asset_status'), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('current_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('commission_date', sa.Date(), nullable=True),
    sa.Column('warranty_end', sa.Date(), nullable=True),
    sa.Column('condition_percent', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('last_repair_date', sa.Date(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('usage_intensity', sa.Integer(), nullable=False),
    sa.Column('is_transfer_locked', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['asset_classes.id'], name=op.f('fk_assets_class_id_asset_classes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_warehouse_id'], ['warehouses.id'], name=op.f('fk_assets_current_warehouse_id_warehouses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['asset_models.id'], name=op.f('fk_assets_model_id_asset_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_assets_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_assets_region_id_regions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_assets_service_id_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_asset_tag'), 'assets', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_assets_class_id'), 'assets', ['class_id'], unique=False)
    op.create_index(op.f('ix_assets_current_warehouse_id'), 'assets', ['current_warehouse_id'], unique=False)
    op.create_index(op.f('ix_assets_model_id'), 'assets', ['model_id'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_assets_region_id'), 'assets', ['region_id'], unique=False)
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=True)
    op.create_index(op.f('ix_assets_service_id'), 'assets', ['service_id'], unique=False)
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_table('asset_assignments',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_assignments_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_asset_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_assignments'))
    )
    op.create_index(op.f('ix_asset_assignments_asset_id'), 'asset_assignments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_assignments_user_id'), 'asset_assignments', ['user_id'], unique=False)
    op.create_index('uq_active_asset_assignment', 'asset_assignments', ['asset_id'], unique=True, postgresql_where=sa.text('unassigned_at IS NULL'))
    op.create_table('asset_history',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_history_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_asset_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_history'))
    )
    op.create_index(op.f('ix_asset_history_asset_id'), 'asset_history', ['asset_id'], unique=False)
    op.create_table('asset_transfers',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'cancelled', name='transferstatus'), nullable=False),
    sa.Column('from_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('to_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('from_service_id', sa.UUID(), nullable=True),
    sa.Column('to_service_id', sa.UUID(), nullable=True),
    sa.Column('transferred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_transfers_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_transfers_created_by_id_users')),
    sa.ForeignKeyConstraint(['from_service_id'], ['services.id'], name=op.f('fk_asset_transfers_from_service_id_services')),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], name=op.f('fk_asset_transfers_from_warehouse_id_warehouses')),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], name=op.f('fk_asset_transfers_received_by_id_users')),
    sa.ForeignKeyConstraint(['to_service_id'], ['services.id'], name=op.f('fk_asset_transfers_to_service_id_services')),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], name=op.f('fk_asset_transfers_to_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_transfers'))
    )
    op.create_index(op.f('ix_asset_transfers_asset_id'), 'asset_transfers', ['asset_id'], unique=False)
    op.create_table('documents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'APPROVED', name='documentstatus'), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_documents_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_documents_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_asset_id'), 'documents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_documents_created_by_id'), 'documents', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_table('repairs',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('reported_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('REPORTED', 'IN_PROGRESS', 'DONE', 'CANCELED', name='repairstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_repairs_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_repairs_assigned_to_id_users')),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], name=op.f('fk_repairs_reported_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repairs'))
    )
    op.create_index(op.f('ix_repairs_asset_id'), 'repairs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_repairs_assigned_to_id'), 'repairs', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_repairs_reported_by_id'), 'repairs', ['reported_by_id'], unique=False)
    op.create_table('document_files',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_files_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_files'))
    )
    op.create_index(op.f('ix_document_files_document_id'), 'document_files', ['document_id'], unique=False)
    op.create_table('repair_parts',
    sa.Column('repair_id', sa.UUID(), nullable=False),
    sa.Column('part_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], name=op.f('fk_repair_parts_repair_id_repairs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repair_parts'))
    )
    op.create_index(op.f('ix_repair_parts_repair_id'), 'repair_parts', ['repair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_parts_repair_id'), table_name='repair_parts')
    op.drop_table('repair_parts')
    op.drop_index(op.f('ix_document_files_document_id'), table_name='document_files')
    op.drop_table('document_files')
    op.drop_index(op.f('ix_repairs_reported_by_id'), table_name='repairs')
    op.drop_index(op.f('ix_repairs_assigned_to_id'), table_name='repairs')
    op.drop_index(op.f('ix_repairs_asset_id'), table_name='repairs')
    op.drop_table('repairs')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_asset_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_asset_transfers_asset_id'), table_name='asset_transfers')
    op.drop_table('asset_transfers')
    op.drop_index(op.f('ix_asset_history_asset_id'), table_name='asset_history')
    op.drop_table('asset_history')
    op.drop_index('uq_active_asset_assignment', table_name='asset_assignments', postgresql_where=sa.text('unassigned_at IS NULL'))
    op.drop_index(op.f('ix_asset_assignments_user_id'), table_name='asset_assignments')
    op.drop_index(op.f('ix_asset_assignments_asset_id'), table_name='asset_assignments')
    op.drop_table('asset_assignments')
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_service_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_region_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_model_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_current_warehouse_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_class_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_tag'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('warehouses')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_user_active', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_expires_at'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_path'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_approval_status_created', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_entity_type'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_entity_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_created_by_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_approved_by_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_action'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('region_services')
    op.drop_index('uq_asset_model_name_lower', table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_name'), table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_manufacturer_id'), table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_category_id'), table_name='asset_models')
    op.drop_table('asset_models')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_table('services')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('regions')
    op.drop_table('ranks')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('uq_manufacturer_name_lower', table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index('uq_asset_class_name_lower', table_name='asset_classes')
    op.drop_table('asset_classes')
    op.drop_index(op.f('ix_asset_categories_code'), table_name='asset_categories')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
