"""

Revision ID: 337b43d6fd0f
Revises: 3b6c2f1a9d4e
Create Date: 2026-06-03 20:18:55.848478

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "337b43d6fd0f"
down_revision: str | Sequence[str] | None = "3b6c2f1a9d4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
