"""

Revision ID: 3619656ca45b
Revises: 6f3b2f5b74da
Create Date: 2026-04-14 09:38:14.447365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3619656ca45b'
down_revision: Union[str, Sequence[str], None] = '6f3b2f5b74da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('query', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'query')
    op.drop_column('audit_logs', 'user_agent')
    # ### end Alembic commands ###
