"""

Revision ID: 45b8c7a16440
Revises: 923852840b2d
Create Date: 2026-05-12 23:52:58.390822

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "45b8c7a16440"
down_revision: str | Sequence[str] | None = "923852840b2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "language",
        existing_type=postgresql.ENUM("RU", "UZ", "EN", name="user_language"),
        server_default=None,
        existing_comment="Interface language",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_comment="Timezone (IANA)",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "theme_preference",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_comment="Theme preference",
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_users_date_of_birth"), table_name="users")
    op.drop_index(op.f("idx_users_department"), table_name="users")
    op.drop_index(op.f("idx_users_employment_type"), table_name="users")
    op.drop_index(op.f("idx_users_language"), table_name="users")
    op.drop_column("users", "avatar_thumbnail_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "avatar_thumbnail_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
            comment="URL miniature avatar",
        ),
    )
    op.create_index(op.f("idx_users_language"), "users", ["language"], unique=False)
    op.create_index(
        op.f("idx_users_employment_type"), "users", ["employment_type"], unique=False
    )
    op.create_index(op.f("idx_users_department"), "users", ["department"], unique=False)
    op.create_index(
        op.f("idx_users_date_of_birth"), "users", ["date_of_birth"], unique=False
    )
    op.alter_column(
        "users",
        "theme_preference",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'light'::character varying"),
        existing_comment="Theme preference",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'Asia/Tashkent'::character varying"),
        existing_comment="Timezone (IANA)",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "language",
        existing_type=postgresql.ENUM("RU", "UZ", "EN", name="user_language"),
        server_default=sa.text("'RU'::user_language"),
        existing_comment="Interface language",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
