"""

Revision ID: 4b6281e5bd8d
Revises: 78f0ca9cea41
Create Date: 2026-04-25 16:18:44.620900

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "4b6281e5bd8d"
down_revision: Union[str, Sequence[str], None] = "78f0ca9cea41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
