"""

Revision ID: 4bd1671e5713
Revises: 914f6ce1204e
Create Date: 2026-05-20 18:55:28.335410

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bd1671e5713"
down_revision: str | Sequence[str] | None = "914f6ce1204e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_component_changes",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("changed_at", sa.Date(), nullable=False),
        sa.Column("old_component", sa.String(length=255), nullable=False),
        sa.Column("new_component", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("changed_by_id", sa.UUID(), nullable=False),
        sa.Column("document_ref", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_component_changes_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
            name=op.f("fk_asset_component_changes_changed_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_component_changes")),
    )
    op.create_index(
        op.f("ix_asset_component_changes_asset_id"),
        "asset_component_changes",
        ["asset_id"],
        unique=False,
    )
    op.create_table(
        "asset_components",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("serial_number", sa.String(length=255), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_components_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_components")),
    )
    op.create_index(
        op.f("ix_asset_components_asset_id"),
        "asset_components",
        ["asset_id"],
        unique=False,
    )
    op.create_table(
        "asset_maintenances",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("maintenance_type", sa.String(length=100), nullable=False),
        sa.Column("performed_at", sa.Date(), nullable=False),
        sa.Column("issues_found", sa.Text(), nullable=True),
        sa.Column("performed_by_id", sa.UUID(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_maintenances_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_id"],
            ["users.id"],
            name=op.f("fk_asset_maintenances_performed_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_maintenances")),
    )
    op.create_index(
        op.f("ix_asset_maintenances_asset_id"),
        "asset_maintenances",
        ["asset_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_asset_maintenances_asset_id"), table_name="asset_maintenances"
    )
    op.drop_table("asset_maintenances")
    op.drop_index(op.f("ix_asset_components_asset_id"), table_name="asset_components")
    op.drop_table("asset_components")
    op.drop_index(
        op.f("ix_asset_component_changes_asset_id"),
        table_name="asset_component_changes",
    )
    op.drop_table("asset_component_changes")
    # ### end Alembic commands ###
