"""

Revision ID: 561131633e26
Revises: b5758846fa95
Create Date: 2026-05-02 00:16:43.425657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561131633e26'
down_revision: Union[str, Sequence[str], None] = 'b5758846fa95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_requests', 'decided_at')
    # ### end Alembic commands ###
