"""

Revision ID: 5ae78ef288c9
Revises: 31c6372d020c
Create Date: 2026-05-04 23:12:49.780245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ae78ef288c9'
down_revision: Union[str, Sequence[str], None] = '31c6372d020c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_rank_id_ranks'), 'users', type_='foreignkey')
    op.drop_column('users', 'rank_id')
    op.drop_table('ranks')

    op.drop_column('approval_requests', 'version')
    op.drop_column('assets', 'version')
    op.drop_column('users', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_users_rank_id_ranks'), 'users', 'ranks', ['rank_id'], ['id'], ondelete='SET NULL')
    op.add_column('assets', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('approval_requests', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('ranks',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranks')),
    sa.UniqueConstraint('code', name=op.f('uq_ranks_code'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('uq_ranks_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
