"""

Revision ID: 65527c60413c
Revises: 28fd9a2c7d4f
Create Date: 2026-05-05 15:03:55.445410

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "65527c60413c"
down_revision: str | Sequence[str] | None = "28fd9a2c7d4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
