"""

Revision ID: 78f0ca9cea41
Revises: 889620cdf06d
Create Date: 2026-04-25 16:02:28.569662

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78f0ca9cea41"
down_revision: str | Sequence[str] | None = "889620cdf06d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_asset_class_name_lower",
        "asset_classes",
        [sa.literal_column("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_asset_class_name_lower", table_name="asset_classes")
    # ### end Alembic commands ###
