"""

Revision ID: 8457085d6096
Revises: 8c968e7b65c2
Create Date: 2026-04-29 22:58:39.418938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8457085d6096"
down_revision: Union[str, Sequence[str], None] = "8c968e7b65c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "approval_requests", sa.Column("version", sa.Integer(), nullable=False)
    )
    op.add_column(
        "approval_requests",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_approval_status_created",
        "approval_requests",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_approval_status_created", table_name="approval_requests")
    op.drop_column("approval_requests", "updated_at")
    op.drop_column("approval_requests", "version")
    # ### end Alembic commands ###
