"""

Revision ID: 889620cdf06d
Revises: a6e671bf09ad
Create Date: 2026-04-25 00:59:06.950101

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "889620cdf06d"
down_revision: str | Sequence[str] | None = "a6e671bf09ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asset_models", sa.Column("code", sa.String(length=150), nullable=False)
    )
    op.create_index(
        op.f("ix_asset_models_name"), "asset_models", ["name"], unique=False
    )
    op.create_index(
        "uq_asset_model_name_lower",
        "asset_models",
        [sa.literal_column("lower(name)"), "manufacturer_id"],
        unique=True,
    )
    op.create_unique_constraint(op.f("uq_asset_models_code"), "asset_models", ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_asset_models_code"), "asset_models", type_="unique")
    op.drop_index("uq_asset_model_name_lower", table_name="asset_models")
    op.drop_index(op.f("ix_asset_models_name"), table_name="asset_models")
    op.drop_column("asset_models", "code")
    # ### end Alembic commands ###
