"""

Revision ID: 914f6ce1204e
Revises: 9e77eae96f44
Create Date: 2026-05-19 15:37:26.084207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914f6ce1204e'
down_revision: Union[str, Sequence[str], None] = '9e77eae96f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_images',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_images_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_images'))
    )
    op.create_index(op.f('ix_asset_images_asset_id'), 'asset_images', ['asset_id'], unique=False)
    op.create_index('ix_asset_images_asset_order', 'asset_images', ['asset_id', 'sort_order'], unique=False)
    op.create_index('ix_asset_images_asset_primary', 'asset_images', ['asset_id', 'is_primary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_images_asset_primary', table_name='asset_images')
    op.drop_index('ix_asset_images_asset_order', table_name='asset_images')
    op.drop_index(op.f('ix_asset_images_asset_id'), table_name='asset_images')
    op.drop_table('asset_images')
    # ### end Alembic commands ###
