"""

Revision ID: 9cd6b89eac04
Revises: d9ac68c274e3
Create Date: 2026-06-04 20:25:12.337130

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9cd6b89eac04"
down_revision: str | Sequence[str] | None = "d9ac68c274e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
