"""

Revision ID: a294f17ee6a0
Revises: f286a3039a04
Create Date: 2026-04-13 23:16:00.309397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a294f17ee6a0'
down_revision: Union[str, Sequence[str], None] = 'f286a3039a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_permissions_code'), 'permissions', type_='unique')
    op.drop_column('permissions', 'code')
    op.drop_constraint(op.f('uq_roles_code'), 'roles', type_='unique')
    op.drop_column('roles', 'code')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('roles', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_roles_code'), 'roles', ['code'], postgresql_nulls_not_distinct=False)
    op.add_column('permissions', sa.Column('code', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_permissions_code'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
