"""

Revision ID: a6e671bf09ad
Revises: 869172b1cafb
Create Date: 2026-04-25 00:28:44.336747

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6e671bf09ad"
down_revision: str | Sequence[str] | None = "869172b1cafb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "manufacturers", sa.Column("code", sa.String(length=150), nullable=False)
    )
    op.drop_index(op.f("ix_manufacturers_name"), table_name="manufacturers")
    op.create_index(
        op.f("ix_manufacturers_name"), "manufacturers", ["name"], unique=False
    )
    op.create_index(
        "uq_manufacturer_name_lower",
        "manufacturers",
        [sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_unique_constraint(
        op.f("uq_manufacturers_code"), "manufacturers", ["code"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_manufacturers_code"), "manufacturers", type_="unique")
    op.drop_index("uq_manufacturer_name_lower", table_name="manufacturers")
    op.drop_index(op.f("ix_manufacturers_name"), table_name="manufacturers")
    op.create_index(
        op.f("ix_manufacturers_name"), "manufacturers", ["name"], unique=True
    )
    op.drop_column("manufacturers", "code")
    # ### end Alembic commands ###
