"""

Revision ID: aae1ea63543c
Revises: a2e0092671ad
Create Date: 2026-04-12 16:14:24.442078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae1ea63543c'
down_revision: Union[str, Sequence[str], None] = 'a2e0092671ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('code', sa.String(length=50), nullable=False))
    op.create_unique_constraint(op.f('uq_roles_code'), 'roles', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_roles_code'), 'roles', type_='unique')
    op.drop_column('roles', 'code')
    # ### end Alembic commands ###
