"""

Revision ID: b122b9d74fad
Revises: bd6194cb2a03
Create Date: 2026-05-05 17:30:36.472746

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b122b9d74fad"
down_revision: str | Sequence[str] | None = "bd6194cb2a03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
