"""

Revision ID: b84fe57b3c68
Revises: d6155cd9c4d0
Create Date: 2026-06-04 20:29:07.921620

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b84fe57b3c68"
down_revision: str | Sequence[str] | None = "d6155cd9c4d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
