"""

Revision ID: b911d8526f88
Revises: d1764a51e388
Create Date: 2026-05-16 00:38:26.683348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b911d8526f88'
down_revision: Union[str, Sequence[str], None] = 'd1764a51e388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_assets_service_class', 'assets', ['service_id', 'class_id'], unique=False)
    op.create_index('ix_assets_status_region', 'assets', ['status', 'region_id'], unique=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('expenses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index('ix_expenses_created_occurred', 'expenses', ['created_at', 'occurred_at'], unique=False)
    op.drop_constraint(op.f('uq_services_code'), 'services', type_='unique')
    op.drop_column('services', 'code')
    op.create_index('ix_users_hired_status', 'users', ['hired_at', 'status'], unique=False)
    op.create_index('ix_users_region_service', 'users', ['assigned_region_id', 'assigned_service_id'], unique=False)
    op.create_index('ix_users_status_role', 'users', ['status', 'role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_status_role', table_name='users')
    op.drop_index('ix_users_region_service', table_name='users')
    op.drop_index('ix_users_hired_status', table_name='users')
    op.add_column('services', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_services_code'), 'services', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_expenses_created_occurred', table_name='expenses')
    op.alter_column('expenses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_assets_status_region', table_name='assets')
    op.drop_index('ix_assets_service_class', table_name='assets')
    # ### end Alembic commands ###
