"""

Revision ID: d1764a51e388
Revises: 45b8c7a16440
Create Date: 2026-05-12 23:53:35.123566

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1764a51e388"
down_revision: str | Sequence[str] | None = "45b8c7a16440"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "theme_preference")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "theme_preference",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
            comment="Theme preference",
        ),
    )
    # ### end Alembic commands ###
