"""

Revision ID: d439d9487294
Revises: a294f17ee6a0
Create Date: 2026-04-13 23:36:20.963153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd439d9487294'
down_revision: Union[str, Sequence[str], None] = 'a294f17ee6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('roles', sa.Column('code', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'code')
    op.drop_column('permissions', 'code')
    # ### end Alembic commands ###
