"""

Revision ID: d6155cd9c4d0
Revises: 9cd6b89eac04
Create Date: 2026-06-04 20:28:28.611653

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d6155cd9c4d0"
down_revision: str | Sequence[str] | None = "9cd6b89eac04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
