"""

Revision ID: d9ac68c274e3
Revises: 337b43d6fd0f
Create Date: 2026-06-03 23:29:28.119868

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9ac68c274e3"
down_revision: str | Sequence[str] | None = "337b43d6fd0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asset_transfers", sa.Column("department_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_asset_transfers_department_id_departments"),
        "asset_transfers",
        "departments",
        ["department_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("assets", sa.Column("department_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_assets_department_id"), "assets", ["department_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_assets_department_id_departments"),
        "assets",
        "departments",
        ["department_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("expenses", sa.Column("department_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_expenses_department_id"), "expenses", ["department_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_expenses_department_id_departments"),
        "expenses",
        "departments",
        ["department_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("users", sa.Column("department_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_users_department_id_departments"),
        "users",
        "departments",
        ["department_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("users", "department")
    op.add_column("warehouses", sa.Column("department_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_warehouses_department_id_departments"),
        "warehouses",
        "departments",
        ["department_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_warehouses_department_id_departments"),
        "warehouses",
        type_="foreignkey",
    )
    op.drop_column("warehouses", "department_id")
    op.add_column(
        "users",
        sa.Column(
            "department",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="Department/division",
        ),
    )
    op.drop_constraint(
        op.f("fk_users_department_id_departments"), "users", type_="foreignkey"
    )
    op.drop_column("users", "department_id")
    op.drop_constraint(
        op.f("fk_expenses_department_id_departments"), "expenses", type_="foreignkey"
    )
    op.drop_index(op.f("ix_expenses_department_id"), table_name="expenses")
    op.drop_column("expenses", "department_id")
    op.drop_constraint(
        op.f("fk_assets_department_id_departments"), "assets", type_="foreignkey"
    )
    op.drop_index(op.f("ix_assets_department_id"), table_name="assets")
    op.drop_column("assets", "department_id")
    op.drop_constraint(
        op.f("fk_asset_transfers_department_id_departments"),
        "asset_transfers",
        type_="foreignkey",
    )
    op.drop_column("asset_transfers", "department_id")
    # ### end Alembic commands ###
