"""

Revision ID: e435e08b9d03
Revises: b911d8526f88
Create Date: 2026-05-16 01:37:59.950803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e435e08b9d03"
down_revision: str | Sequence[str] | None = "b911d8526f88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("services", sa.Column("code", sa.String(length=50), nullable=True))
    op.create_unique_constraint(op.f("uq_services_code"), "services", ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_services_code"), "services", type_="unique")
    op.drop_column("services", "code")
    # ### end Alembic commands ###
