"""

Revision ID: e682bc2e6c94
Revises: 3e347d55c907
Create Date: 2026-05-27 23:11:07.195346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e682bc2e6c94'
down_revision: Union[str, Sequence[str], None] = '3e347d55c907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_components_asset_id'), table_name='asset_components')
    op.drop_table('asset_components')
    op.drop_index(op.f('ix_asset_component_changes_asset_id'), table_name='asset_component_changes')
    op.drop_table('asset_component_changes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_component_changes',
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('changed_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('old_component', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('new_component', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('changed_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_component_changes_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_asset_component_changes_changed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_component_changes'))
    )
    op.create_index(op.f('ix_asset_component_changes_asset_id'), 'asset_component_changes', ['asset_id'], unique=False)
    op.create_table('asset_components',
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_components_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_components'))
    )
    op.create_index(op.f('ix_asset_components_asset_id'), 'asset_components', ['asset_id'], unique=False)
    # ### end Alembic commands ###
