"""

Revision ID: facaa46811da
Revises: aae1ea63543c
Create Date: 2026-04-12 16:58:13.950890

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'facaa46811da'
down_revision: Union[str, Sequence[str], None] = 'aae1ea63543c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('service_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_warehouses_service_id_services'), 'warehouses', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_warehouses_service_id_services'), 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'service_id')
    # ### end Alembic commands ###
